Not providing any token in requests results in wrong error message
gorilla/csrf pull request #149
Opened 2021-02-01 12:41 UTC by FlorianLoch

I am sorry I did not create an issue before, I was not aware of this. Also I consider this a very minor fix so I hope this is okay.

The problem is the following: not providing any token with a request results in ```ErrBadToken``` being given to the error handler. While technically not being wrong that really is not what to be expected when there is an ```ErrNoToken``` (which actually never gets returned, see below). It would have saved myself quite some hours of debugging knowing the token did not make it to the backend due to some nginx setting discarding headers with non-compliant names instead of assuming the token is invalid (due to whatever reason).

While being at the code I realised that the only time ```ErrNoToken``` being used in the code so far never gets executed (if I did not miss something massively) due to a condition never becoming true.

I want to furthermore annotate

**Summary of Changes**

1. extend tests to verify the problem
2. extend signature of  ```helpers.requestToken()``` to also return ```error``` to differentiate between an empty/non-existing 
token and an actual error
3. check for empty token and raise ```ErrNoToken```
4. remove conditional never becoming true 
5.  added myself to the AUTHORS file. I am not craving for fame and I am not vain either, I just assumed it to be good style with this repo. Please drop this if I am wrong.

2021-03-09 19:19 UTC, FlorianLoch commented
Any feedback on this?

2021-04-11 13:46 UTC, elithrar requested changes
Minor style nit.

2021-04-11 13:46 UTC, elithrar commented on csrf.go
> +
Remove the empty line here.

2021-04-11 15:50 UTC, FlorianLoch commented on csrf.go
> +
I agree on this ;)

2021-04-30 15:30 UTC, lastthyme approved these changes

2021-06-03 21:49 UTC, FlorianLoch commented
Are we good to go? ;)

2021-07-29 15:49 UTC, elithrar approved these changes
Thanks for this @FlorianLoch - !

2021-07-29 15:50 UTC, merged